/**
 * This code was generated by Builder.io.
 */
import React from 'react';

import Header from '@components/mya/organisms/Header';

import OrderSummary from '@/components/mya/molecules/Checkout/OrderSummary';
import Footer from '@components/mya/organisms/Footer';
import ProductCartSection from '@components/mya/organisms/ProductCartSection';

interface CartPageProps {
  productCart: any[];
}

const CartPage: React.FC<CartPageProps> = ({ productCart }) => {
  return (
    <div className="flex flex-col h-full bg-white w-screen">
      <Header/>
      <div className="flex flex-grow flex-col lg:flex-row px-8 lg:px-32 py-8">
      <main className="flex lg:w-[70%] mx-auto flex-grow">
        <ProductCartSection products={productCart} />
      </main>
      <hr className="w-full lg:w-[70%] lg:hidden mx-auto border-t border-gray-300 my-8" />
      <aside className="w-full lg:w-[30%] mx-auto">
        <OrderSummary totalProducts={99} subtotal="Rp.9.900.000,00" totalPayment="Rp.9.900.000,00" />
      </aside>
      </div>
        {/* <Footer /> */}
    </div>
  );
};

export default CartPage;