/**
 * This code was generated by Builder.io.
 */
import React from 'react';

import Header from '@components/mya/organisms/Header';

import OrderSummary from '@/components/mya/molecules/Checkout/OrderSummary';
import VirtualAccount from '@components/mya/molecules/Checkout/VirtualAccount';
import TransferGuide from '@components/mya/molecules/Checkout/TransferGuide';
import PaymentSuccess from '@components/mya/molecules/Checkout/PaymentSuccess';
import ProductPaymentSection from '@/components/mya/organisms/ProductCheckoutSection';

interface CheckoutPageProps {
  products: any[];
}

const CheckoutPage: React.FC<CheckoutPageProps> = ({ products }) => {
  return (
    <div className="flex flex-col h-full bg-white w-screen">
      <Header />
      <div className="flex flex-grow flex-col lg:flex-row px-8 lg:px-32 py-8">
      <main className="flex lg:w-[70%] mx-auto flex-grow">
        <ProductPaymentSection products={products} />
      </main>
      <hr className="w-full lg:w-[70%] lg:hidden mx-auto border-t border-gray-300 my-8" />
      <aside className="w-full lg:w-[30%] mx-auto">
        <VirtualAccount virtualAccount='1234567890' />
        <hr className="w-full border-t border-gray-300 my-6" />
        <OrderSummary totalProducts={99} subtotal="Rp.9.900.000,00" totalPayment="Rp.9.900.000,00" isCheckout />
        <hr className="w-full border-t border-gray-300 my-6" />
        <TransferGuide />
        <hr className="w-full border-t border-gray-300 my-6" />
        <PaymentSuccess />

      </aside>
      </div>
        {/* <Footer /> */}
    </div>
  );
};

export default CheckoutPage;