/**
 * This code was generated by Builder.io.
 */
import React from 'react';

import Header from '@components/mya/organisms/Header';
import Hero from '@components/mya/organisms/Hero';
import DetailSection from '@components/mya/organisms/DetailSection';
import ProductSection from '@components/mya/organisms/ProductSection';
import Footer from '@components/mya/organisms/Footer';

interface DetailPageProps {
  logo: string;
  relatedProducts: any[];
  heroData: any;
  product: any;
}

const DetailPage: React.FC<DetailPageProps> = ({ logo, product, relatedProducts, heroData }) => {
  return (
    <div className="flex flex-col h-full bg-white w-screen">
      <Header logo={logo} />
      <main className="flex flex-col w-full h-full">
        <DetailSection product={product} />
        <ProductSection title="Produk Lainnya" products={relatedProducts} isDetail />
        <Hero heroData={heroData} />
        <Footer />
      </main>
    </div>
  );
};

export default DetailPage;