/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { Image as NextUIImage, ImageProps as NextUIImageProps } from "@nextui-org/react";

interface ImageProps extends NextUIImageProps {}

const Image: React.FC<ImageProps> = (props) => {
  return <NextUIImage {...props} />;
};

export default Image;